### ISSUE TITLE
認証エラーが発生する

### ISSUE THREAD

**Issue by Shungo-Matsueda** [KazuSh1geru/desktop-screenshoter#28]
なぜか自分の環境で実行しようとすると認証エラーが発生する

```
Traceback (most recent call last):
  File "/Users/shungo-matsueda/dev/desktop-screenshoter/src/main.py", line 62, in <module>
    main()
  File "/Users/shungo-matsueda/dev/desktop-screenshoter/src/main.py", line 35, in main
    send_image_to_thread(latest_screenshot)
  File "/Users/shungo-matsueda/dev/desktop-screenshoter/src/slack_client.py", line 27, in send_image_to_thread
    _ = client.files_upload_v2(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/client.py", line 3678, in files_upload_v2
    url_response = self.files_getUploadURLExternal(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/client.py", line 3746, in files_getUploadURLExternal
    return self.api_call("files.getUploadURLExternal", params=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/base_client.py", line 157, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/base_client.py", line 188, in _sync_send
    return self._urllib_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/base_client.py", line 319, in _urllib_api_call
    ).validate()
      ^^^^^^^^^^
  File "/Users/shungo-matsueda/Library/Caches/pypoetry/virtualenvs/desktop-screenshoter-6jF0AUhc-py3.12/lib/python3.12/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://slack.com/api/files.getUploadURLExternal)
The server responded with: {'ok': False, 'error': 'invalid_auth'}
```

**Comment by KazuSh1geru** [comment]
松枝PCでSlack Appへのリクエストが通らない
